/**
 * Freeze the latest real workspace into a static snapshot the web app can serve
 * as a no-backend demo (for the Congressional App Challenge judges). Picks the
 * most active company, normalizes anything still "live" to ended so nothing
 * animates, strips the real license key, and writes a typed snapshot module.
 *
 * Usage: pnpm --filter @taro/api exec tsx src/scripts/export-demo.ts
 */
import '../config/env';
import fs from 'fs';
import path from 'path';
import { connectDB, mongoose } from '../db/mongo';
import {
  CompanyModel,
  SlackConnectionModel,
  GithubConnectionModel,
  MeetingModel,
  ActionLogModel,
} from '../db/models';
import { DEFAULT_GITHUB_ACTIONS } from '@taro/shared';

const DEMO_KEY = 'TARO-DEMO-CAC1-2026';
const OUT = path.resolve(__dirname, '../../../../apps/web/src/demo/snapshot.ts');

async function main() {
  await connectDB();

  // Pick the company with the most recorded commands, then the most meetings.
  const companies = await CompanyModel.find().lean();
  const scored = [];
  for (const c of companies) {
    const meetings = await MeetingModel.countDocuments({ companyId: c._id, archivedAt: { $exists: false } });
    const logs = await ActionLogModel.countDocuments({ companyId: c._id });
    scored.push({ c, meetings, logs });
  }
  scored.sort((a, b) => b.logs - a.logs || b.meetings - a.meetings);
  scored.forEach((s) => console.log(`  ${s.c.name} <${s.c.domain}>  meetings=${s.meetings} commands=${s.logs}`));
  const chosen = scored[0];
  if (!chosen) throw new Error('No companies found');
  const companyId = chosen.c._id;
  console.log(`\nChosen: ${chosen.c.name} (${companyId})`);

  const slack = await SlackConnectionModel.findOne({ companyId }).lean();
  const github = await GithubConnectionModel.findOne({ companyId }).lean();

  // Include archived meetings: this workspace's real commands live on meetings
  // that were later cleared, and the demo should show them as history.
  const meetingsRaw = await MeetingModel.find({ companyId })
    .sort({ createdAt: -1 })
    .limit(50)
    .lean();

  const meetings = [];
  const details: Record<string, { actionLogs: unknown[] }> = {};
  for (const m of meetingsRaw as Array<Record<string, unknown> & { _id: unknown }>) {
    // Static snapshot: nothing is actually live, so present every meeting as history.
    const status = m.status === 'ended' ? 'ended' : m.status === 'error' ? 'error' : 'ended';
    const meeting = {
      _id: String(m._id),
      companyId: String(m.companyId),
      meetUrl: m.meetUrl,
      status,
      startedByName: m.startedByName,
      transcript: m.transcript,
      createdAt: m.createdAt,
      updatedAt: m.updatedAt,
      startedAt: m.startedAt,
      endedAt: m.endedAt,
    };
    meetings.push(meeting);

    const logs = await ActionLogModel.find({ meetingId: m._id }).sort({ createdAt: -1 }).limit(50).lean();
    details[String(m._id)] = {
      ...meeting,
      actionLogs: logs.map((l) => ({
        _id: String(l._id),
        command: l.command,
        intent: l.intent,
        status: l.status,
        result: l.result,
        errorMessage: l.errorMessage,
        createdAt: l.createdAt,
      })),
    };
  }

  const snapshot = {
    demoKey: DEMO_KEY,
    capturedAt: new Date().toISOString(),
    company: {
      _id: String(chosen.c._id),
      name: chosen.c.name,
      domain: chosen.c.domain,
      licenseKey: DEMO_KEY, // never expose the real key in a public demo
      onboardedAt: chosen.c.onboardedAt,
      createdAt: chosen.c.createdAt,
      updatedAt: chosen.c.updatedAt,
    },
    slack: {
      connected: !!slack,
      teamName: slack?.teamName,
      connectedAt: slack?.createdAt,
    },
    github: {
      connected: !!(github?.installationId && !github?.disconnectedAt),
      configured: true,
      accountLogin: github?.accountLogin,
      repo: github?.repo,
      needsRepo: !github?.repo,
      enabledActions:
        github?.enabledActions && github.enabledActions.length > 0
          ? github.enabledActions
          : DEFAULT_GITHUB_ACTIONS,
      connectedAt: github?.createdAt,
    },
    meetings,
    details,
  };

  const banner = '// AUTO-GENERATED by scripts/export-demo.ts. A frozen snapshot of real\n// workspace data for the no-backend demo. Regenerate, do not hand-edit.\n';
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, `${banner}export const snapshot = ${JSON.stringify(snapshot, null, 2)} as const;\n`);
  console.log(`\nWrote ${OUT}`);
  const totalLogs = Object.values(details).reduce((n, d) => n + (d as { actionLogs: unknown[] }).actionLogs.length, 0);
  console.log(`Meetings: ${meetings.length}, commands captured: ${totalLogs}`);
  console.log('\nSample commands:');
  Object.values(details)
    .flatMap((d) => (d as { actionLogs: { command: string; status: string; intent: { action: string } }[] }).actionLogs)
    .slice(0, 8)
    .forEach((l) => console.log(`  [${l.status}] ${l.intent.action}: "${String(l.command).slice(0, 70)}"`));

  await mongoose.disconnect();
  process.exit(0);
}

main().catch((error) => {
  console.error('Export failed:', error);
  process.exit(1);
});
