// AUTO-GENERATED by scripts/export-demo.ts. A frozen snapshot of real
// workspace data for the no-backend demo. Regenerate, do not hand-edit.
export const snapshot = {
  "demoKey": "TARO-DEMO-CAC1-2026",
  "capturedAt": "2026-08-29T22:53:34.269Z",
  "company": {
    "_id": "692bb7734fa4c0adbe4118fc",
    "name": "VacantCourt",
    "domain": "vacantcourt.com",
    "licenseKey": "TARO-DEMO-CAC1-2026",
    "onboardedAt": "2026-08-22T23:19:37.376Z",
    "createdAt": "2025-11-30T03:18:11.461Z",
    "updatedAt": "2026-08-22T23:19:37.377Z"
  },
  "slack": {
    "connected": true,
    "teamName": "VacantCourt",
    "connectedAt": "2026-08-26T03:59:10.104Z"
  },
  "github": {
    "connected": true,
    "configured": true,
    "accountLogin": "sohan-bhat",
    "repo": "sohan-bhat/VacantCourt",
    "needsRepo": false,
    "enabledActions": [
      "create_github_issue",
      "comment_github",
      "close_github_issue",
      "reopen_github_issue",
      "label_github_issue",
      "assign_github_issue",
      "close_pull_request",
      "merge_pull_request",
      "request_github_review",
      "create_pull_request"
    ],
    "connectedAt": "2026-08-24T02:52:02.099Z"
  },
  "meetings": [
    {
      "_id": "6a8e568d83915237bbf1cb83",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/sxu-ajhx-wzj",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep! Hey Taro, can you go ahead and introduce yourself to the social channel on Slack? hey taro go ahead and create a new github branch Hey, Taro, can you go ahead and create a new pull request domain on GitHub? Hey, Taro, can you go ahead and make a GitHub pull request to Maine?",
      "createdAt": "2026-08-26T02:59:25.371Z",
      "updatedAt": "2026-08-26T03:37:57.334Z",
      "startedAt": "2026-08-26T02:59:46.323Z",
      "endedAt": "2026-08-26T03:16:03.420Z"
    },
    {
      "_id": "6a8e45381feb40feab1720f0",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/jcm-ntkj-nxg",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep. Hey, Taro. go ahead and introduce yourself to the social channel on Slack. Hey, Taro, go ahead and create a pull request domain on GitHub.",
      "createdAt": "2026-08-26T01:45:28.170Z",
      "updatedAt": "2026-08-26T03:37:57.334Z",
      "startedAt": "2026-08-26T01:45:51.106Z",
      "endedAt": "2026-08-26T01:48:56.757Z"
    },
    {
      "_id": "6a8bb7d4185e869a75b5c57e",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hyq-dyae-hio",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep! go ahead and introduce yourself. A taro. go ahead and introduce yourself to the social channel on Slack. Hey Tara, go ahead and introduce yourself to the social team on Slack. Hey, Taro. go ahead and create a GitHub issue referring to customer dissatisfaction.",
      "createdAt": "2026-08-24T03:17:40.317Z",
      "updatedAt": "2026-08-26T03:37:57.334Z",
      "startedAt": "2026-08-24T03:18:00.289Z",
      "endedAt": "2026-08-24T03:32:48.740Z"
    },
    {
      "_id": "6a8bb701185e869a75b5c1a7",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hwh-tuex-hkc",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep! and introduce yourself to the social channel on Slack. Hey, Tara. go ahead and introduce yourself to the social channel on Slack. Hey Tara, go ahead and create a GitHub issue talking about customer dissatisfaction.",
      "createdAt": "2026-08-24T03:14:09.648Z",
      "updatedAt": "2026-08-24T03:17:30.014Z",
      "startedAt": "2026-08-24T03:14:30.536Z",
      "endedAt": "2026-08-24T03:17:30.014Z"
    },
    {
      "_id": "6a8bb30c90ec1a2bdaa62fc6",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/zpo-qkoq-qnv",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "createdAt": "2026-08-24T02:57:16.332Z",
      "updatedAt": "2026-08-24T03:05:12.129Z",
      "startedAt": "2026-08-24T02:57:29.815Z"
    },
    {
      "_id": "6a8bb23690ec1a2bdaa62c6f",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/miv-ruxb-qqi",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep. Hey, Tara, can you go ahead and introduce yourself to the social channel on Slack?",
      "createdAt": "2026-08-24T02:53:42.984Z",
      "updatedAt": "2026-08-24T02:55:57.075Z",
      "startedAt": "2026-08-24T02:53:58.971Z",
      "endedAt": "2026-08-24T02:55:57.075Z"
    },
    {
      "_id": "6a8b8ea9fef4173a30c7ef2f",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hss-qrqr-vzb",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep. POST to Slack, create a GitHub. Hey Taro, go ahead and say hi to the team for me in the social channel on Slack. Very nice. And can you go ahead and create a pull request on GitHub and title it recent Mobile update changes for me. Hey Taro, can you go ahead and do that? What initial request did you do? Hey Taro, can you go ahead and make a pull request on Github, titling it Mobile Update Changes? Hey Taro, can you go ahead and make an issue on GitHub for me, titling it Mobile Update Changes?",
      "createdAt": "2026-08-24T00:22:01.168Z",
      "updatedAt": "2026-08-24T01:39:26.029Z",
      "startedAt": "2026-08-24T00:22:18.417Z",
      "endedAt": "2026-08-24T00:26:15.273Z"
    },
    {
      "_id": "6a8b5b309d78319bf427d20b",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hzu-uczu-drh",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "AND AND AND AND OH YES HE HE HE HE AND AND AND HAY TARO IN THE SOCIAL CHANNEL ON SLACK AND YOU GO AHEAD AND ON TALK ABOUT AH TO DAY'S WEATHER AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND HEY TARO IN THE SOCIAL CHANNEL ON SLACK GO AHEAD AND A TYPE ONE PLUS ONE AND AND AND AND AND AND AND HE TARO INDI A OM SOCIAL CHANNEL AND SLACK GO AHEAD AND WRITE THE EQUATION ONCE A SWAN AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND",
      "createdAt": "2026-08-23T20:42:24.943Z",
      "updatedAt": "2026-08-24T01:39:26.029Z",
      "startedAt": "2026-08-23T20:42:42.410Z",
      "endedAt": "2026-08-23T20:45:58.434Z"
    },
    {
      "_id": "6a8a76a375aef4f983026dfb",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/tht-rkvb-jwm",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "createdAt": "2026-08-23T04:27:15.456Z",
      "updatedAt": "2026-08-23T17:48:16.951Z",
      "startedAt": "2026-08-23T04:27:39.773Z",
      "endedAt": "2026-08-23T17:46:21.262Z"
    },
    {
      "_id": "6a8a71f4eca65a167f3775e1",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/fqq-ansk-pfu",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "createdAt": "2026-08-23T04:07:16.725Z",
      "updatedAt": "2026-08-23T17:48:16.951Z",
      "endedAt": "2026-08-23T17:46:21.520Z"
    },
    {
      "_id": "6a8a6ee7ecfef0b18e9624bc",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/fqq-ansk-pfu",
      "status": "ended",
      "createdAt": "2026-08-23T03:54:15.046Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T03:55:06.706Z",
      "endedAt": "2026-08-23T04:05:21.873Z"
    },
    {
      "_id": "6a8a6cf6c442e18296a5f819",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/xpk-voqq-sgn",
      "status": "ended",
      "transcript": "Hey Taro, in the social channel UM, write your opinion about today's weather.",
      "createdAt": "2026-08-23T03:45:58.888Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T03:46:34.328Z",
      "endedAt": "2026-08-23T03:47:21.301Z"
    },
    {
      "_id": "6a8a69ea336bacf2161dd46f",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/ehd-uihk-qjy",
      "status": "ended",
      "transcript": "Hey Taro, in the Socials channel, make a quick statement about, um, what day it is today. Furthermore, um, make a GitHub issue about the recent all customer complaints. About a product.",
      "createdAt": "2026-08-23T03:32:58.041Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T03:33:50.076Z",
      "endedAt": "2026-08-23T03:39:09.120Z"
    },
    {
      "_id": "6a8a61623aae31e4f3885bc4",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/xri-xiet-kwv",
      "status": "ended",
      "transcript": "Yes, there's been a pretty big issue about that topic, actually. Um. Hey, Taro, can you go ahead and... A post Hello team to the social channel Hey Tara, go ahead and post hello. Saying in the social channel. And yeah, there have been pretty big issues about that overall, um, the main issue was like, the fact, our product. Our customers were not happy with our product. Hey, Taro, can you go ahead and make a GitHub repository? Sorry, GitHub issue about that.",
      "createdAt": "2026-08-23T02:56:34.314Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T02:57:18.263Z",
      "endedAt": "2026-08-23T02:59:14.602Z"
    },
    {
      "_id": "6a8a36f014bcc05f409e0b40",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/kze-uuyf-ppv",
      "status": "ended",
      "transcript": "On the last arm project, can you go ahead and create, uh, an issue for me on GitHub talking about how, um, this app does not work for Mobile edition. Hey, Taro. Create an issue, on GitHub. On how my app does not work on Mobile edition.",
      "createdAt": "2026-08-22T23:55:28.309Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-22T23:56:19.050Z",
      "endedAt": "2026-08-22T23:59:55.271Z"
    },
    {
      "_id": "6a8a3475ea8e6e3ac580b0b0",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/fjt-pjsx-qgp",
      "status": "ended",
      "transcript": "Hey Taro, can you create a GitHub issue for me? About the button not working on Safari?",
      "createdAt": "2026-08-22T23:44:53.156Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-22T23:45:55.054Z",
      "endedAt": "2026-08-22T23:48:12.146Z"
    },
    {
      "_id": "6a61331e0532e73eedb34eef",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/uvh-xmxg-nfy",
      "status": "ended",
      "transcript": "Hey, Taro. Send a message on the Meetings channel. Talking about how great cats are. Hey, Taro. Make a to-do list in the Meetings channel. About testing and the demo and recording the video.",
      "createdAt": "2026-07-22T21:16:14.148Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-07-22T21:17:11.790Z",
      "endedAt": "2026-07-22T21:19:28.773Z"
    },
    {
      "_id": "6a61321e6933bf1e9f93bbd7",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/uvh-xmxg-nfy",
      "status": "error",
      "createdAt": "2026-07-22T21:11:58.412Z",
      "updatedAt": "2026-08-23T04:05:52.825Z"
    }
  ],
  "details": {
    "6a8e568d83915237bbf1cb83": {
      "_id": "6a8e568d83915237bbf1cb83",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/sxu-ajhx-wzj",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep! Hey Taro, can you go ahead and introduce yourself to the social channel on Slack? hey taro go ahead and create a new github branch Hey, Taro, can you go ahead and create a new pull request domain on GitHub? Hey, Taro, can you go ahead and make a GitHub pull request to Maine?",
      "createdAt": "2026-08-26T02:59:25.371Z",
      "updatedAt": "2026-08-26T03:37:57.334Z",
      "startedAt": "2026-08-26T02:59:46.323Z",
      "endedAt": "2026-08-26T03:16:03.420Z",
      "actionLogs": [
        {
          "_id": "6a8e57fe83915237bbf1cd49",
          "command": "can you go ahead and make a github pull request to maine?",
          "intent": {
            "action": "create_pull_request",
            "confidence": 0.86,
            "params": {
              "title": "Merge changes into maine",
              "body": "## Summary\nThis pull request merges the current work into the `maine` branch as requested during the meeting.\n\n## Changes\n- [ ] Implement the updates intended for the maine branch"
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Opened PR #21 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/pull/21",
          "createdAt": "2026-08-26T03:05:34.521Z"
        },
        {
          "_id": "6a8e57c883915237bbf1ccf4",
          "command": "can you go ahead and create a new pull request domain on github?",
          "intent": {
            "action": "create_pull_request",
            "confidence": 0.9,
            "params": {
              "title": "Domain updates",
              "body": "## Summary\nThis pull request introduces the requested domain-related changes to the codebase, addressing the need discussed in the meeting.\n\n## Changes\n- [ ] Implement domain updates\n- [ ] Add tests for domain functionality\n- [ ] Update documentation for domain changes"
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Opened PR #20 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/pull/20",
          "createdAt": "2026-08-26T03:04:40.364Z"
        },
        {
          "_id": "6a8e577183915237bbf1ccb0",
          "command": "go ahead and create a new github branch",
          "intent": {
            "action": "unknown",
            "confidence": 0.9,
            "params": {
              "reason": "The request is to create a new GitHub branch, but there is no supported action for branch creation; I can create a pull request which creates a branch, but cannot create a branch alone.",
              "original": "go ahead and create a new github branch"
            },
            "source": "groq"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-26T03:03:13.144Z"
        },
        {
          "_id": "6a8e56c883915237bbf1cc53",
          "command": "can you go ahead and introduce yourself to the social channel on slack?",
          "intent": {
            "action": "post_message",
            "confidence": 0.96,
            "params": {
              "channel": "social",
              "message": "Hi everyone! I'm Taro, your voice‑activated meeting assistant. I'm here to help you post updates, manage GitHub issues and pull requests, and keep track of todos. Feel free to say “Hey Taro” whenever you need a hand."
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Posted \"Hi everyone! I'm Taro, your voice‑activated meeting assistant. I'm here to help you post updates, manage GitHub issues and pull requests, and keep track of todos. Feel free to say “Hey Taro” whenever you need a hand.\" to #social",
          "createdAt": "2026-08-26T03:00:24.502Z"
        }
      ]
    },
    "6a8e45381feb40feab1720f0": {
      "_id": "6a8e45381feb40feab1720f0",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/jcm-ntkj-nxg",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep. Hey, Taro. go ahead and introduce yourself to the social channel on Slack. Hey, Taro, go ahead and create a pull request domain on GitHub.",
      "createdAt": "2026-08-26T01:45:28.170Z",
      "updatedAt": "2026-08-26T03:37:57.334Z",
      "startedAt": "2026-08-26T01:45:51.106Z",
      "endedAt": "2026-08-26T01:48:56.757Z",
      "actionLogs": [
        {
          "_id": "6a8e45911feb40feab1721a2",
          "command": "go ahead and create a pull request domain on github.",
          "intent": {
            "action": "create_pull_request",
            "confidence": 0.86,
            "params": {
              "title": "Add domain feature",
              "body": "## Summary\nCreate a pull request to introduce the domain-related changes discussed. This PR captures the implementation of the new domain feature and prepares it for review before merging into the main branch.\n\n## Changes\n- [ ] Add domain model and related classes\n- [ ] Implement domain validation logic\n- [ ] Update documentation for domain usage\n- [ ] Write unit tests for domain functionality"
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Opened PR #19 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/pull/19",
          "createdAt": "2026-08-26T01:46:57.787Z"
        },
        {
          "_id": "6a8e45721feb40feab172105",
          "command": "go ahead and introduce yourself to the social channel on slack.",
          "intent": {
            "action": "post_message",
            "confidence": 0.96,
            "params": {
              "channel": "social",
              "message": "Hi everyone! I'm Taro, the voice‑activated meeting assistant. I'm here to help capture action items, create GitHub issues, post updates, and handle other tasks. Just say “Hey Taro” whenever you need a hand."
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Posted \"Hi everyone! I'm Taro, the voice‑activated meeting assistant. I'm here to help capture action items, create GitHub issues, post updates, and handle other tasks. Just say “Hey Taro” whenever you need a hand.\" to #social",
          "createdAt": "2026-08-26T01:46:26.553Z"
        }
      ]
    },
    "6a8bb7d4185e869a75b5c57e": {
      "_id": "6a8bb7d4185e869a75b5c57e",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hyq-dyae-hio",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep! go ahead and introduce yourself. A taro. go ahead and introduce yourself to the social channel on Slack. Hey Tara, go ahead and introduce yourself to the social team on Slack. Hey, Taro. go ahead and create a GitHub issue referring to customer dissatisfaction.",
      "createdAt": "2026-08-24T03:17:40.317Z",
      "updatedAt": "2026-08-26T03:37:57.334Z",
      "startedAt": "2026-08-24T03:18:00.289Z",
      "endedAt": "2026-08-24T03:32:48.740Z",
      "actionLogs": [
        {
          "_id": "6a8bb8fa185e869a75b5c877",
          "command": "go ahead and create a github issue referring to customer dissatisfaction.",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.86,
            "params": {
              "title": "Investigate customer dissatisfaction",
              "body": "## Summary\nCustomers have reported dissatisfaction that needs to be addressed.\n"
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Opened issue #18 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/18",
          "createdAt": "2026-08-24T03:22:34.055Z"
        },
        {
          "_id": "6a8bb8c4185e869a75b5c772",
          "command": "go ahead and introduce yourself to the social team on slack.",
          "intent": {
            "action": "post_message",
            "confidence": 0.96,
            "params": {
              "channel": "social",
              "message": "Hi everyone! I'm Taro, your voice‑activated meeting assistant. I'm here to help with posting updates, managing GitHub issues, and creating to‑do lists. Let me know how I can assist you!"
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Posted \"Hi everyone! I'm Taro, your voice‑activated meeting assistant. I'm here to help with posting updates, managing GitHub issues, and creating to‑do lists. Let me know how I can assist you!\" to #social",
          "createdAt": "2026-08-24T03:21:40.058Z"
        }
      ]
    },
    "6a8bb701185e869a75b5c1a7": {
      "_id": "6a8bb701185e869a75b5c1a7",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hwh-tuex-hkc",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep! and introduce yourself to the social channel on Slack. Hey, Tara. go ahead and introduce yourself to the social channel on Slack. Hey Tara, go ahead and create a GitHub issue talking about customer dissatisfaction.",
      "createdAt": "2026-08-24T03:14:09.648Z",
      "updatedAt": "2026-08-24T03:17:30.014Z",
      "startedAt": "2026-08-24T03:14:30.536Z",
      "endedAt": "2026-08-24T03:17:30.014Z",
      "actionLogs": [
        {
          "_id": "6a8bb790185e869a75b5c43f",
          "command": "go ahead and create a github issue talking about customer dissatisfaction.",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.93,
            "params": {
              "title": "Customer dissatisfaction",
              "body": "## Summary\nCustomers have expressed dissatisfaction with the product."
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Opened issue #17 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/17",
          "createdAt": "2026-08-24T03:16:32.413Z"
        },
        {
          "_id": "6a8bb74c185e869a75b5c304",
          "command": "go ahead and introduce yourself to the social channel on slack.",
          "intent": {
            "action": "post_message",
            "confidence": 0.96,
            "params": {
              "channel": "social",
              "message": "Hi everyone! I'm Taro, the voice‑activated meeting assistant. I'm here to help capture notes, manage tasks, and handle GitHub issues directly from our conversations. Looking forward to working with you all!"
            },
            "source": "groq"
          },
          "status": "success",
          "result": "Posted \"Hi everyone! I'm Taro, the voice‑activated meeting assistant. I'm here to help capture notes, manage tasks, and handle GitHub issues directly from our conversations. Looking forward to working with you all!\" to #social",
          "createdAt": "2026-08-24T03:15:24.355Z"
        }
      ]
    },
    "6a8bb30c90ec1a2bdaa62fc6": {
      "_id": "6a8bb30c90ec1a2bdaa62fc6",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/zpo-qkoq-qnv",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "createdAt": "2026-08-24T02:57:16.332Z",
      "updatedAt": "2026-08-24T03:05:12.129Z",
      "startedAt": "2026-08-24T02:57:29.815Z",
      "actionLogs": [
        {
          "_id": "6a8bb4b790ec1a2bdaa63711",
          "command": "can you go ahead and create a github issue around customer dissatisfaction?",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.85,
            "params": {
              "title": "Around customer dissatisfaction"
            },
            "source": "fallback_regex"
          },
          "status": "success",
          "result": "Opened issue #16 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/16",
          "createdAt": "2026-08-24T03:04:23.695Z"
        },
        {
          "_id": "6a8bb43390ec1a2bdaa634a0",
          "command": "can you go ahead and create a new github issue about how the mobile app is not functioning correctly?",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.85,
            "params": {
              "title": "How the mobile app is not functioning correctly"
            },
            "source": "fallback_regex"
          },
          "status": "success",
          "result": "Opened issue #15 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/15",
          "createdAt": "2026-08-24T03:02:11.533Z"
        },
        {
          "_id": "6a8bb3bd90ec1a2bdaa6324b",
          "command": "can you go ahead and create a pull request on github to main? for the demo.",
          "intent": {
            "action": "unknown",
            "confidence": 0,
            "params": {
              "original": "can you go ahead and create a pull request on github to main? for the demo."
            },
            "source": "fallback_regex"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-24T03:00:13.696Z"
        },
        {
          "_id": "6a8bb34d90ec1a2bdaa630b0",
          "command": "can you go ahead and introduce yourself to the social channel on slack?",
          "intent": {
            "action": "post_message",
            "confidence": 0.95,
            "params": {
              "channel": "social",
              "message": "Hello everyone! I'm Taro, your voice-activated meeting assistant."
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Posted \"Hello everyone! I'm Taro, your voice-activated meeting assistant.\" to #social",
          "createdAt": "2026-08-24T02:58:21.234Z"
        }
      ]
    },
    "6a8bb23690ec1a2bdaa62c6f": {
      "_id": "6a8bb23690ec1a2bdaa62c6f",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/miv-ruxb-qqi",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep. Hey, Tara, can you go ahead and introduce yourself to the social channel on Slack?",
      "createdAt": "2026-08-24T02:53:42.984Z",
      "updatedAt": "2026-08-24T02:55:57.075Z",
      "startedAt": "2026-08-24T02:53:58.971Z",
      "endedAt": "2026-08-24T02:55:57.075Z",
      "actionLogs": [
        {
          "_id": "6a8bb29690ec1a2bdaa62dfc",
          "command": "can you go ahead and introduce yourself to the social channel on slack?",
          "intent": {
            "action": "post_message",
            "confidence": 0.9,
            "params": {
              "channel": "social",
              "message": "Hi everyone! I'm Taro, your voice-activated meeting assistant. I'm excited to be here and help assist with your meetings and team workflows!"
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Posted \"Hi everyone! I'm Taro, your voice-activated meeting assistant. I'm excited to be here and help assist with your meetings and team workflows!\" to #social",
          "createdAt": "2026-08-24T02:55:18.153Z"
        }
      ]
    },
    "6a8b8ea9fef4173a30c7ef2f": {
      "_id": "6a8b8ea9fef4173a30c7ef2f",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hss-qrqr-vzb",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "Beep. POST to Slack, create a GitHub. Hey Taro, go ahead and say hi to the team for me in the social channel on Slack. Very nice. And can you go ahead and create a pull request on GitHub and title it recent Mobile update changes for me. Hey Taro, can you go ahead and do that? What initial request did you do? Hey Taro, can you go ahead and make a pull request on Github, titling it Mobile Update Changes? Hey Taro, can you go ahead and make an issue on GitHub for me, titling it Mobile Update Changes?",
      "createdAt": "2026-08-24T00:22:01.168Z",
      "updatedAt": "2026-08-24T01:39:26.029Z",
      "startedAt": "2026-08-24T00:22:18.417Z",
      "endedAt": "2026-08-24T00:26:15.273Z",
      "actionLogs": [
        {
          "_id": "6a8b8f78fef4173a30c7f2c3",
          "command": "can you go ahead and make an issue on github for me, titling it mobile update changes?",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.95,
            "params": {
              "title": "Implement mobile update changes",
              "body": "## Summary\nThis issue tracks the implementation of mobile update changes requested during the meeting. It serves as a placeholder to coordinate and execute the required mobile updates.\n\n## Details\nNo specific error codes, target browsers, or technical parameters were detailed during the voice prompt context.\n\n## Next steps\n- [ ] Clarify specific mobile update requirements\n- [ ] Implement the mobile update changes\n- [ ] Verify and review updates"
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Opened issue #12 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/12",
          "createdAt": "2026-08-24T00:25:28.496Z"
        },
        {
          "_id": "6a8b8f4dfef4173a30c7f1ea",
          "command": "can you go ahead and make a pull request on github, titling it mobile update changes?",
          "intent": {
            "action": "unknown",
            "confidence": 0.1,
            "params": {
              "original": "can you go ahead and make a pull request on github, titling it mobile update changes?"
            },
            "source": "gemini"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-24T00:24:45.147Z"
        },
        {
          "_id": "6a8b8f37fef4173a30c7f187",
          "command": "can you go ahead and do that? what initial request did you do?",
          "intent": {
            "action": "unknown",
            "confidence": 0.1,
            "params": {
              "original": "can you go ahead and do that? what initial request did you do?"
            },
            "source": "gemini"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-24T00:24:23.528Z"
        },
        {
          "_id": "6a8b8f06fef4173a30c7f095",
          "command": "go ahead and say hi to the team for me in the social channel on slack.",
          "intent": {
            "action": "post_message",
            "confidence": 0.95,
            "params": {
              "channel": "social",
              "message": "Hi team!"
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Posted \"Hi team!\" to #social",
          "createdAt": "2026-08-24T00:23:34.978Z"
        }
      ]
    },
    "6a8b5b309d78319bf427d20b": {
      "_id": "6a8b5b309d78319bf427d20b",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/hzu-uczu-drh",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "transcript": "AND AND AND AND OH YES HE HE HE HE AND AND AND HAY TARO IN THE SOCIAL CHANNEL ON SLACK AND YOU GO AHEAD AND ON TALK ABOUT AH TO DAY'S WEATHER AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND HEY TARO IN THE SOCIAL CHANNEL ON SLACK GO AHEAD AND A TYPE ONE PLUS ONE AND AND AND AND AND AND AND HE TARO INDI A OM SOCIAL CHANNEL AND SLACK GO AHEAD AND WRITE THE EQUATION ONCE A SWAN AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND AND",
      "createdAt": "2026-08-23T20:42:24.943Z",
      "updatedAt": "2026-08-24T01:39:26.029Z",
      "startedAt": "2026-08-23T20:42:42.410Z",
      "endedAt": "2026-08-23T20:45:58.434Z",
      "actionLogs": [
        {
          "_id": "6a8b5bc19d78319bf427d408",
          "command": "indi a om social channel and slack go ahead and write the equation once a swan",
          "intent": {
            "action": "unknown",
            "confidence": 0.1,
            "params": {
              "original": "indi a om social channel and slack go ahead and write the equation once a swan"
            },
            "source": "gemini"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-23T20:44:49.711Z"
        },
        {
          "_id": "6a8b5bb19d78319bf427d3ec",
          "command": "in the social channel on slack",
          "intent": {
            "action": "unknown",
            "confidence": 0.1,
            "params": {
              "original": "in the social channel on slack"
            },
            "source": "gemini"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-23T20:44:33.165Z"
        },
        {
          "_id": "6a8b5b6f9d78319bf427d2fa",
          "command": "in the social channel on slack and you go ahead and on",
          "intent": {
            "action": "unknown",
            "confidence": 0,
            "params": {
              "original": "in the social channel on slack and you go ahead and on"
            },
            "source": "fallback_regex"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-23T20:43:27.120Z"
        }
      ]
    },
    "6a8a76a375aef4f983026dfb": {
      "_id": "6a8a76a375aef4f983026dfb",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/tht-rkvb-jwm",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "createdAt": "2026-08-23T04:27:15.456Z",
      "updatedAt": "2026-08-23T17:48:16.951Z",
      "startedAt": "2026-08-23T04:27:39.773Z",
      "endedAt": "2026-08-23T17:46:21.262Z",
      "actionLogs": [
        {
          "_id": "6a8a772475aef4f983026fdc",
          "command": "n the social channel post",
          "intent": {
            "action": "unknown",
            "confidence": 0.3,
            "params": {
              "original": "n the social channel post"
            },
            "source": "gemini"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-23T04:29:24.965Z"
        },
        {
          "_id": "6a8a771e75aef4f983026fb0",
          "command": "n the social channel",
          "intent": {
            "action": "unknown",
            "confidence": 0,
            "params": {
              "original": "n the social channel"
            },
            "source": "fallback_regex"
          },
          "status": "clarification_needed",
          "createdAt": "2026-08-23T04:29:18.716Z"
        }
      ]
    },
    "6a8a71f4eca65a167f3775e1": {
      "_id": "6a8a71f4eca65a167f3775e1",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/fqq-ansk-pfu",
      "status": "ended",
      "startedByName": "Sohan Bhat",
      "createdAt": "2026-08-23T04:07:16.725Z",
      "updatedAt": "2026-08-23T17:48:16.951Z",
      "endedAt": "2026-08-23T17:46:21.520Z",
      "actionLogs": []
    },
    "6a8a6ee7ecfef0b18e9624bc": {
      "_id": "6a8a6ee7ecfef0b18e9624bc",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/fqq-ansk-pfu",
      "status": "ended",
      "createdAt": "2026-08-23T03:54:15.046Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T03:55:06.706Z",
      "endedAt": "2026-08-23T04:05:21.873Z",
      "actionLogs": []
    },
    "6a8a6cf6c442e18296a5f819": {
      "_id": "6a8a6cf6c442e18296a5f819",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/xpk-voqq-sgn",
      "status": "ended",
      "transcript": "Hey Taro, in the social channel UM, write your opinion about today's weather.",
      "createdAt": "2026-08-23T03:45:58.888Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T03:46:34.328Z",
      "endedAt": "2026-08-23T03:47:21.301Z",
      "actionLogs": [
        {
          "_id": "6a8a6d72c442e18296a5fa58",
          "command": "in the social channel um, write your opinion about today's weather.",
          "intent": {
            "action": "post_message",
            "confidence": 0.9,
            "params": {
              "channel": "social",
              "message": "Write your opinion about today's weather."
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Posted \"Write your opinion about today's weather.\" to #social",
          "createdAt": "2026-08-23T03:48:02.070Z"
        }
      ]
    },
    "6a8a69ea336bacf2161dd46f": {
      "_id": "6a8a69ea336bacf2161dd46f",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/ehd-uihk-qjy",
      "status": "ended",
      "transcript": "Hey Taro, in the Socials channel, make a quick statement about, um, what day it is today. Furthermore, um, make a GitHub issue about the recent all customer complaints. About a product.",
      "createdAt": "2026-08-23T03:32:58.041Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T03:33:50.076Z",
      "endedAt": "2026-08-23T03:39:09.120Z",
      "actionLogs": [
        {
          "_id": "6a8a6bac336bacf2161ddc1f",
          "command": "in the socials channel, make a quick statement about, um, what day it is today. furthermore, um, make a github issue about the recent all customer complaints. about a product.",
          "intent": {
            "action": "post_message",
            "confidence": 0.8,
            "params": {
              "channel": "socials",
              "message": "What day it is today."
            },
            "source": "gemini"
          },
          "status": "failed",
          "errorMessage": "Channel \"socials\" not found",
          "createdAt": "2026-08-23T03:40:28.198Z"
        }
      ]
    },
    "6a8a61623aae31e4f3885bc4": {
      "_id": "6a8a61623aae31e4f3885bc4",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/xri-xiet-kwv",
      "status": "ended",
      "transcript": "Yes, there's been a pretty big issue about that topic, actually. Um. Hey, Taro, can you go ahead and... A post Hello team to the social channel Hey Tara, go ahead and post hello. Saying in the social channel. And yeah, there have been pretty big issues about that overall, um, the main issue was like, the fact, our product. Our customers were not happy with our product. Hey, Taro, can you go ahead and make a GitHub repository? Sorry, GitHub issue about that.",
      "createdAt": "2026-08-23T02:56:34.314Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-23T02:57:18.263Z",
      "endedAt": "2026-08-23T02:59:14.602Z",
      "actionLogs": [
        {
          "_id": "6a8a625b3aae31e4f3885ee5",
          "command": "can you go ahead and make a github repository? sorry, github issue about that.",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.75,
            "params": {
              "title": "Address customer dissatisfaction with the product",
              "body": "## Summary\nDuring the meeting, it was highlighted that customers are currently unhappy with the product, which is posing a major issue overall. This issue was created to track and address this feedback.\n\n## Details\n- **Impact:** Customers expressed dissatisfaction with the product.\n- **Source:** Discussed during live meeting context."
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Created issue #11 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/11",
          "createdAt": "2026-08-23T03:00:43.472Z"
        },
        {
          "_id": "6a8a624b3aae31e4f3885ea0",
          "command": "go ahead and post hello. saying in the social channel. and yeah, there have been pretty big issues about that overall, um, the main issue was like, the fact, our product. our customers were not happy with our product.",
          "intent": {
            "action": "post_message",
            "confidence": 0.85,
            "params": {
              "channel": "social",
              "message": "Hello team."
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Posted \"Hello team.\" to #social",
          "createdAt": "2026-08-23T03:00:27.547Z"
        },
        {
          "_id": "6a8a62343aae31e4f3885e2f",
          "command": "can you go ahead and... a post hello team to the social channel",
          "intent": {
            "action": "post_message",
            "confidence": 0.9,
            "params": {
              "channel": "social",
              "message": "hello team"
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Posted \"hello team\" to #social",
          "createdAt": "2026-08-23T03:00:04.944Z"
        }
      ]
    },
    "6a8a36f014bcc05f409e0b40": {
      "_id": "6a8a36f014bcc05f409e0b40",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/kze-uuyf-ppv",
      "status": "ended",
      "transcript": "On the last arm project, can you go ahead and create, uh, an issue for me on GitHub talking about how, um, this app does not work for Mobile edition. Hey, Taro. Create an issue, on GitHub. On how my app does not work on Mobile edition.",
      "createdAt": "2026-08-22T23:55:28.309Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-22T23:56:19.050Z",
      "endedAt": "2026-08-22T23:59:55.271Z",
      "actionLogs": [
        {
          "_id": "6a8a388014bcc05f409e11fe",
          "command": "create an issue, on github. on how my app does not work on mobile edition.",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.9,
            "params": {
              "title": "App does not work on mobile edition"
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Created issue #10 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/10",
          "createdAt": "2026-08-23T00:02:08.136Z"
        }
      ]
    },
    "6a8a3475ea8e6e3ac580b0b0": {
      "_id": "6a8a3475ea8e6e3ac580b0b0",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/fjt-pjsx-qgp",
      "status": "ended",
      "transcript": "Hey Taro, can you create a GitHub issue for me? About the button not working on Safari?",
      "createdAt": "2026-08-22T23:44:53.156Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-08-22T23:45:55.054Z",
      "endedAt": "2026-08-22T23:48:12.146Z",
      "actionLogs": [
        {
          "_id": "6a8a3561ea8e6e3ac580b3e7",
          "command": "can you create a github issue for me? about the button not working on safari?",
          "intent": {
            "action": "create_github_issue",
            "confidence": 0.9,
            "params": {
              "title": "Button not working on Safari"
            },
            "source": "gemini"
          },
          "status": "success",
          "result": "Created issue #9 in sohan-bhat/VacantCourt: https://github.com/sohan-bhat/VacantCourt/issues/9",
          "createdAt": "2026-08-22T23:48:49.293Z"
        }
      ]
    },
    "6a61331e0532e73eedb34eef": {
      "_id": "6a61331e0532e73eedb34eef",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/uvh-xmxg-nfy",
      "status": "ended",
      "transcript": "Hey, Taro. Send a message on the Meetings channel. Talking about how great cats are. Hey, Taro. Make a to-do list in the Meetings channel. About testing and the demo and recording the video.",
      "createdAt": "2026-07-22T21:16:14.148Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "startedAt": "2026-07-22T21:17:11.790Z",
      "endedAt": "2026-07-22T21:19:28.773Z",
      "actionLogs": [
        {
          "_id": "6a6134100532e73eedb34fcd",
          "command": "make a to-do list in the meetings channel. about testing and the demo and recording the video.",
          "intent": {
            "action": "create_todo_list",
            "confidence": 0.9,
            "params": {
              "channel": "meetings",
              "items": [
                "Testing",
                "The demo",
                "Record the video"
              ]
            },
            "source": "gemini"
          },
          "status": "failed",
          "errorMessage": "Channel \"meetings\" not found",
          "createdAt": "2026-07-22T21:20:16.461Z"
        },
        {
          "_id": "6a61340d0532e73eedb34fca",
          "command": "send a message on the meetings channel. talking about how great cats are.",
          "intent": {
            "action": "post_message",
            "confidence": 0.95,
            "params": {
              "channel": "meetings",
              "message": "talking about how great cats are"
            },
            "source": "gemini"
          },
          "status": "failed",
          "errorMessage": "Channel \"meetings\" not found",
          "createdAt": "2026-07-22T21:20:13.486Z"
        }
      ]
    },
    "6a61321e6933bf1e9f93bbd7": {
      "_id": "6a61321e6933bf1e9f93bbd7",
      "companyId": "692bb7734fa4c0adbe4118fc",
      "meetUrl": "https://meet.google.com/uvh-xmxg-nfy",
      "status": "error",
      "createdAt": "2026-07-22T21:11:58.412Z",
      "updatedAt": "2026-08-23T04:05:52.825Z",
      "actionLogs": []
    }
  }
} as const;
